### ISSUE TITLE
Typo in cf.png

### ISSUE THREAD

**Issue by alex-rolfe-alloy** [epiccoleman/react-circle-of-fifths#8]
In the diminished wheel in your `cf.png`, the "1-o-clock" position F diminished should be an F# diminished, F# being 1 fifth from B.

Cool project!

**Comment by epiccoleman** [comment]
Ack! This is like the third time I've had to correct that - it's my fault for taking screenshots from old commits while writing blog posts about the component. Will fix - thanks so much for the feedback!

**Comment by epiccoleman** [comment]
Fixed in version [1.0.1](https://github.com/epiccoleman/react-circle-of-fifths/releases/tag/1.0.1). Thanks @alex-rolfe-alloy for helping make this component better!
